name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ opened, reopened, synchronize, edited ]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        directory:
          - 'event-scraper'
          - 'applications-service'
    steps:
      - name: Run git checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Figure out if anything in this directory changed
        if: github.event_name != 'push'
        uses: technote-space/get-diff-action@v4.0.2
        id: git-diff
        with:
          PATTERNS: ${{ matrix.directory }}/**
          DOT: ..

      - name: Set up Node
        uses: actions/setup-node@v2
        if: github.event_name == 'push' || steps.git-diff.outputs.diff
        with:
          node-version: '14.x'
      - run: npm ci
        if: github.event_name == 'push' || steps.git-diff.outputs.diff
        working-directory: ${{ matrix.directory }}
      - run: npm test
        if: github.event_name == 'push' || steps.git-diff.outputs.diff
        working-directory: ${{ matrix.directory }}
    
  auto-merge:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: patch
          github-token: ${{ secrets.mytoken }}